--- 
  backend: 
    branch: master
    commit_messages: 
      create: "Create {{collection}} “{{slug}}”"
      delete: "Delete {{collection}} “{{slug}}”"
      deleteMedia: "[skip ci] Delete “{{path}}”"
      update: "Update {{collection}} “{{slug}}”"
      uploadMedia: "[skip ci] Upload “{{path}}”"
    name: git-gateway
  collections: 
    - 
      files: 
        - 
          fields: 
            - 
              default: index-page
              label: "Template Key"
              name: templateKey
              widget: hidden
            - 
              label: "Hero"
              name: hero
              widget: object
              fields: 
                - 
                  label: Image
                  name: image
                  widget: image
                - 
                  label: Caption
                  name: caption
                  widget: string
                - 
                  label: CTA
                  name: cta
                  widget: string
            - 
              label: Services
              name: services
              widget: list
              fields:
                - 
                  label: Title
                  name: title
                  widget: string
                - 
                  label: Content
                  name: content
                  widget: text
                - 
                  label: Image
                  name: image
                  widget: image
            - 
              label: Contact
              name: contact
              widget: object
              fields: 
                - 
                  label: Heading
                  name: heading
                  widget: string
                -
                  label: Content
                  name: content
                  widget: text
                - 
                  label: Address
                  name: address
                  widget: object
                  fields: 
                    - 
                      label: Name
                      name: name
                      widget: string
                    - 
                      label: Street
                      name: street
                      widget: string
                    - 
                      label: "Zip code"
                      name: zip
                      widget: string
                    - 
                      label: City
                      name: city
                      widget: string
                    - 
                      label: Phone
                      name: phonenumber
                      widget: string
                    - 
                      label: Email
                      name: email
                      widget: string
          file: src/pages/index.md
          label: "Home Page"
          name: index
      label: Pages
      name: pages
  media_folder: static/img
  public_folder: /img
  